"""Browse and switch projects.

    GET  /api/projects            the projects folder, plus the project serve started with
    GET  /api/projects/current    the project every other route is working on
    POST /api/projects/{id}/open  work on that project from now on
"""

import os
from pathlib import Path

from fastapi import APIRouter
from pydantic import BaseModel, Field

from benchlog.core.project import CIRCUIT_PATH, Project, ProjectError
from benchlog.core.repo import GitError
from benchlog.demo import is_demo
from benchlog.server.deps import ProjectDep, open_project, workspace

router = APIRouter(prefix="/api/projects", tags=["projects"])


class ProjectSummary(BaseModel):
    """Matches the web UI's ProjectSummary, plus a few extras."""

    id: str = Field(description="Folder name; what /open takes.")
    name: str
    board: str
    updated: str | None = Field(description="ISO date of the last commit, if any.")
    setupComplete: bool = Field(description="A camera calibration is saved for this project.")  # noqa: N815
    path: str
    open: bool = Field(description="The project the other routes are working on.")
    demo: bool = Field(description="Generated by `benchlog demo seed` (browse only; not the board on the bench).")


def _name(root: Path) -> str:
    """The README's title, else the folder name."""
    readme = root / "README.md"
    if readme.exists():
        first = readme.read_text().splitlines()[0:1]
        if first and first[0].startswith("# "):
            return first[0][2:].strip()
    return root.name.replace("-", " ").replace("_", " ").title()


def _summary(root: Path, current: Path | None) -> ProjectSummary:
    project = Project.find(root)
    last = project.repo.log(limit=1)
    return ProjectSummary(
        id=root.name,
        name=_name(root),
        board=project.load_circuit().board,
        updated=last[0].date if last else None,
        setupComplete=project.calibration_dir.exists(),
        path=str(root),
        open=current is not None and root == current,
        demo=is_demo(root),
    )


def _candidates() -> dict[str, Path]:
    """Project folder name -> path: the workspace's projects, and the one serve started with."""
    found: dict[str, Path] = {}
    folder = workspace()
    if folder is not None and folder.is_dir():
        for child in sorted(folder.iterdir()):
            if (child / CIRCUIT_PATH).exists() and (child / ".git").exists():
                found[child.name] = child.resolve()
    started = os.environ.get("BENCHLOG_PROJECT")
    if started:
        root = Path(started).resolve()
        found.setdefault(root.name, root)
    return found


def _current() -> Path | None:
    from benchlog.server.deps import get_project

    try:
        return get_project().repo.root
    except (ProjectError, GitError):
        return None


@router.get("")
def list_projects() -> list[ProjectSummary]:
    current = _current()
    summaries = []
    for root in _candidates().values():
        try:
            summaries.append(_summary(root, current))
        except (ProjectError, GitError):
            continue  # a broken folder shouldn't hide the others
    return sorted(summaries, key=lambda p: (not p.open, p.demo, p.name.lower()))


@router.get("/current")
def current_project(project: ProjectDep) -> ProjectSummary:
    return _summary(project.repo.root, project.repo.root)


@router.post("/{project_id}/open")
def open_by_id(project_id: str) -> ProjectSummary:
    root = _candidates().get(project_id)
    if root is None:
        raise ProjectError(f"no project {project_id!r} in the projects folder")
    Project.find(root)  # fail here, not on the next request
    open_project(root)
    return _summary(root, root)
